### ISSUE TITLE
Private uploads and syntax highlighting

### ISSUE THREAD

**Issue by lfaoro** [hohl/sourcedrop-osx#7] opened 2014-09-07 14:52 UTC
Ability to control Gist options:
- Syntax Highlighting language {right now SourceDrop has the Syntax highlight option but it doesn't work as my Gists are always generated as Text}
- Option to make Gists private

**Comment by hohl** [comment] 2015-01-24 16:57
Duplicate of issue #3

**Closed by hohl** 2015-01-24 16:57 UTC
